p2pd: remove unused variables
src/p2pd.c:412:12: warning: variable ‘vtime’ set but not used [-Wunused-but-set-variable]
src/p2pd.c:622:23: warning: variable ‘origIp’ set but not used [-Wunused-but-set-variable]
src/p2pd.c:617:22: error: unused variable ‘src’ [-Werror=unused-variable]

Signed-off-by: Ferry Huberts <f.huberts@mindef.nl>