olsr_cookie: introduce OLSR_COOKIE_DEBUG define
src/olsr_cookie.c:213:9: error: variable ‘reuse’ set but not used [-Werror=unused-but-set-variable]
src/olsr_cookie.c:273:9: error: variable ‘reuse’ set but not used [-Werror=unused-but-set-variable]

Signed-off-by: Ferry Huberts <f.huberts@mindef.nl>